# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

question = Question.create(question: '¿Por qué se produce una inundación?', reason: 'Una inundación es una crecida repentina de agua en una región dada, debido a cuestiones climáticas como lluvias, temporales, huracanes, etc')
Answer.create(question: question, answer: 'Por cuestiones climáticas', value: true)
Answer.create(question: question, answer: 'Porque comí demasiado helado', value: false)
Answer.create(question: question, answer: 'Porque no hice mi tarea', value: false)
Answer.create(question: question, answer: 'Porque no me porte bien', value: false)

question = Question.create(question: '¿Qué es una inundación?', reason: 'Una inundación es una crecida repentina de agua en una región dada, debido a cuestiones climáticas como lluvias, temporales, huracanes, etc')
Answer.create(question: question, answer: 'Es la crecida repentina de agua', value: true)
Answer.create(question: question, answer: 'Una banda de rock', value: false)
Answer.create(question: question, answer: 'Un evento climatológico de vientos muy fuertes', value: false)
Answer.create(question: question, answer: 'Un movimiento del piso por placas tectónicas', value: false)

question = Question.create(question: '¿Qué debo hacer si el agua llega a los enchufes?', reason: 'Cortar el suministro eléctrico es lo primero que se debe hacer si el agua entra a tu casa ya que podría haber riesgo de electrocutarse')
Answer.create(question: question, answer: 'Cortar la luz', value: true)
Answer.create(question: question, answer: 'Enchufar la tele', value: false)
Answer.create(question: question, answer: 'Jugar con el celu', value: false)
Answer.create(question: question, answer: 'Leer un libro', value: false)

question = Question.create(question: '¿Qué debo agarrar si hay que subir al techo?', reason: 'Es fundamental al momento de subir a un techo estar bien abrigados, ya que en estos casos la gente quedar varada toda una noche y sufrir de hipotermia')
Answer.create(question: question, answer: 'Ropa seca y abrigos', value: true)
Answer.create(question: question, answer: 'La consola', value: false)
Answer.create(question: question, answer: 'Los peluches', value: false)
Answer.create(question: question, answer: 'El microondas', value: false)

question = Question.create(question: '¿Cómo puedo prevenir una hipotermia?', reason: 'Al momento de empezar a mostrar síntomas de hipotermia, es primordial abrigar a la persona con la mayor cantidad de ropa seca posible')
Answer.create(question: question, answer: 'Cambiarse la ropa mojada por seca', value: true)
Answer.create(question: question, answer: 'Tirarse al agua', value: false)
Answer.create(question: question, answer: 'Quedarse quieto', value: false)
Answer.create(question: question, answer: 'Tomar gaseosa fría', value: false)

question = Question.create(question: '¿Qué es una hipotermia?', reason: 'La hipotermia es una urgencia médica que ocurre cuando el cuerpo pierde calor más rápido de lo que lo produce, lo que provoca una peligrosa disminución de la temperatura corporal')
Answer.create(question: question, answer: 'Es una caída drástica de la temperatura corporal', value: true)
Answer.create(question: question, answer: 'Es una enfermedad hereditaria', value: false)
Answer.create(question: question, answer: 'Es una enfermedad mental', value: false)
Answer.create(question: question, answer: 'Es el nombre de un juego de cartas muy famoso', value: false)

question = Question.create(question: '¿Por qué se produce una hipotermia?', reason: 'La causa de la hipotermia suele ser la exposición al clima frío o la inmersión en agua fría')
Answer.create(question: question, answer: 'Por exposición prolongada al frío', value: true)
Answer.create(question: question, answer: 'Por un golpe en la cabeza', value: false)
Answer.create(question: question, answer: 'Por una exposición a temperaturas altas', value: false)
Answer.create(question: question, answer: 'Por estar demasiado tiempo sin tomar agua', value: false)

question = Question.create(question: '¿Cómo ayudar a alguien que cayó al agua?', reason: 'Al momento de tener que socorrer a alguien que se está ahogando, lo mejor es utilizar una soga, ya que de lo contrario podríamos ser arrastrados nosotros también')
Answer.create(question: question, answer: 'Alcanzarlo arrojando una soga', value: true)
Answer.create(question: question, answer: 'Alcanzarlo estirando mi mano', value: false)
Answer.create(question: question, answer: 'Alcanzarlo con un palo', value: false)
Answer.create(question: question, answer: 'Gritarle para alentarlo', value: false)

question = Question.create(question: '¿Qué hacer en caso de que el agua siga subiendo?', reason: 'Es primordial que en caso de que el agua suba cortar el suministro eléctrico, levantar los muebles (en caso de ser posible) e ir al lugar más alto de la casa para no estar en contacto con el agua')
Answer.create(question: question, answer: 'Todas son correctas', value: true)
Answer.create(question: question, answer: 'Ir al lugar más alto posible', value: false)
Answer.create(question: question, answer: 'Levantar electrodomésticos', value: false)
Answer.create(question: question, answer: 'Cortar el suministro eléctrico', value: false)

question = Question.create(question: '¿Qué es RCP?', reason: 'Es una técnica para salvar vidas que es útil en muchas emergencias, la cual consiste en masaje cardiaco y asistencia respiratoria')
Answer.create(question: question, answer: 'Es una técnica de reanimación cardio respiratoria', value: true)
Answer.create(question: question, answer: 'Son las siglas de un club de fútbol', value: false)
Answer.create(question: question, answer: 'Es el nombre de un programa de TV', value: false)
Answer.create(question: question, answer: 'Son las siglas de una organización', value: false)

question = Question.create(question: '¿Qué cosas debo tomar en caso de tener que irme de casa?', reason: 'Las recomendaciones por parte de las autoridades son tomar lo esencial como botiquín y ropa seca, y además tener un radio con pilas para estar atento a novedades')
Answer.create(question: question, answer: 'Todas son correctas', value: true)
Answer.create(question: question, answer: 'Radio con pilas', value: false)
Answer.create(question: question, answer: 'Ropa seca', value: false)
Answer.create(question: question, answer: 'Botiquín', value: false)

question = Question.create(question: '¿Qué hacer con las mascotas en caso de inundación?', reason: 'Siempre se recomienda no dejar a las mascotas solas en caso de una inundación ya que correrían riesgos de ahogarse o morir de frío')
Answer.create(question: question, answer: 'Llevarlas con nosotros a un lugar alto', value: true)
Answer.create(question: question, answer: 'Dejarlas en el patio', value: false)
Answer.create(question: question, answer: 'Dejarlas en la calle', value: false)
Answer.create(question: question, answer: 'Ignorarlas', value: false)

question = Question.create(question: '¿A quién debo llamar primero en caso de una inundación?', reason: 'Ante un evento como una inundación siempre se recomienda llamar a emergencias para poder ser asistidos cuanto antes')
Answer.create(question: question, answer: 'Emergencias', value: true)
Answer.create(question: question, answer: 'Mi abuela', value: false)
Answer.create(question: question, answer: 'Mi mejor amigo', value: false)
Answer.create(question: question, answer: 'Al pastor del barrio', value: false)

question = Question.create(question: '¿Qué debo hacer con los electrodomésticos en caso de inundación?', reason: 'Ante la entrada de agua a la casa, los electrodomésticos enchufados pueden causar un cortocircuito y electrocutar a alguien')
Answer.create(question: question, answer: 'Desenchufarlos y alejarlos del agua', value: true)
Answer.create(question: question, answer: 'Dejarlos donde están', value: false)
Answer.create(question: question, answer: 'Utilizarlos de bote', value: false)
Answer.create(question: question, answer: 'Encenderlos', value: false)

question = Question.create(question: '¿En qué lugares es recomendable permanecer?', reason: 'En el caso de una inundación, siempre se aconseja ir a los lugares más altos posibles')
Answer.create(question: question, answer: 'En lugares altos', value: true)
Answer.create(question: question, answer: 'En el sótano', value: false)
Answer.create(question: question, answer: 'En la pileta', value: false)
Answer.create(question: question, answer: 'En la cama', value: false)

question = Question.create(question: '¿Cuál de los siguientes objetos no pertenece a un botiquín?', reason: 'Tanto el alcohol, las vendas como el agua oxigenada son objetos fundamentales que no deberían faltar en un botiquín')
Answer.create(question: question, answer: 'Destornillador', value: true)
Answer.create(question: question, answer: 'Alcohol', value: false)
Answer.create(question: question, answer: 'Vendas', value: false)
Answer.create(question: question, answer: 'Agua oxigenada', value: false)

question = Question.create(question: '¿Cuál es el calzado recomendado para caminar en una inundación?', reason: 'El calzado recomendado para las inundaciones son las botas de goma, ya que pueden mantenerte aislado tanto del agua como de objetos cortantes y la electricidad')
Answer.create(question: question, answer: 'Botas de goma', value: true)
Answer.create(question: question, answer: 'Ojotas', value: false)
Answer.create(question: question, answer: 'Pantuflas', value: false)
Answer.create(question: question, answer: 'Ningun calzado', value: false)

question = Question.create(question: '¿Qué debo hacer si estoy lastimado en una inundación?', reason: 'Es muy importante que si hay alguien lastimado en una inundación, se consiga un botiquín de primeros auxilios, se evite el contacto con el agua sucia y no tocar la herida con manos sucias')
Answer.create(question: question, answer: 'Todas son correctas', value: true)
Answer.create(question: question, answer: 'Evitar el contacto del agua con la lastimadura', value: false)
Answer.create(question: question, answer: 'Conseguir un botiquín', value: false)
Answer.create(question: question, answer: 'No tocar la herida con manos sucias', value: false)

question = Question.create(question: '¿Cómo se recomienda aplicar RCP en casos de emergencias?', reason: 'Según el ministerio de salud argentino, lo recomendable para realizar rcp es hacerlo en 30 masajes cardíacos durante 5 ciclos a un ritmo de 100 a 120 compresiones por minuto')
Answer.create(question: question, answer: '30 masajes cardíacos por 5 ciclos', value: true)
Answer.create(question: question, answer: '60 masajes cardíacos por 10 ciclos', value: false)
Answer.create(question: question, answer: '90 masajes cardíacos por 15 ciclos', value: false)
Answer.create(question: question, answer: '120 masajes cardíacos por 20 ciclos', value: false)

question = Question.create(question: '¿Qué debo hacer en caso de correntada?', reason: 'Una de las cosas más peligrosas en una inundación son las correntadas, ya que es la causa por la cual mucha gente muere ahogada. Lo aconsejable es mantenerse lejos del agua')
Answer.create(question: question, answer: 'Evitar entrar al agua', value: true)
Answer.create(question: question, answer: 'Entrar con el kayak', value: false)
Answer.create(question: question, answer: 'Nadar', value: false)
Answer.create(question: question, answer: 'Cargar botellas para tomar', value: false)

question = Question.create(question: '¿Cómo identificar una corriente?', reason: 'Al arrojar un objeto flotante al agua, se puede identificar fácilmente si existe una correntada')
Answer.create(question: question, answer: 'Tirando un palo en el agua', value: true)
Answer.create(question: question, answer: 'Tirandote al agua', value: false)
Answer.create(question: question, answer: 'Tirando otra persona al agua', value: false)
Answer.create(question: question, answer: 'Tirando ropa seca al agua', value: false)

question = Question.create(question: '¿Por qué es tan peligrosa la idea de nadar en una inundación?', reason: 'Nadar en una inundación es muy mala idea ya que podrías quedar atascado por objetos que pasan debajo del agua, podrías electrocutarte por algún cable o incluso lastimarte')
Answer.create(question: question, answer: 'Todas son correctas', value: true)
Answer.create(question: question, answer: 'Porque te puedes atascar', value: false)
Answer.create(question: question, answer: 'Porque te puedes electrocutar', value: false)
Answer.create(question: question, answer: 'Porque te puedes cortar', value: false)

question = Question.create(question: '¿Qué debo hacer una vez que la inundación pase y yo haya estado en el agua?', reason: 'Es aconsejable que toda persona que haya estado en contacto con el agua sucia, acuda a un centro médico cercano para que le apliquen las vacunas correspondientes y evitar enfermedades')
Answer.create(question: question, answer: 'Vacunarse con antitetánica', value: true)
Answer.create(question: question, answer: 'Nada', value: false)
Answer.create(question: question, answer: 'Jugar con el agua sucia', value: false)
Answer.create(question: question, answer: 'Ir a jugar con mis amigos', value: false)

question = Question.create(question: '¿Qué sitios de la casa debo evitar en una inundación?', reason: 'Es primordial que en caso de que el agua suba ir al lugar más alto de la casa para no estar en contacto con el agua')
Answer.create(question: question, answer: 'Todas son correctas', value: true)
Answer.create(question: question, answer: 'El sótano', value: false)
Answer.create(question: question, answer: 'Lugares cerrados', value: false)
Answer.create(question: question, answer: 'La pileta', value: false)

question = Question.create(question: '¿Cómo debo estar calzado en caso de tener que cortar el suministro eléctrico?', reason: 'El calzado recomendado para las inundaciones son las botas de goma, ya que pueden mantenerte aislado tanto del agua como de objetos cortantes y la electricidad')
Answer.create(question: question, answer: 'Calzado de goma', value: true)
Answer.create(question: question, answer: 'Descalzo', value: false)
Answer.create(question: question, answer: 'Ojotas', value: false)
Answer.create(question: question, answer: 'Pantuflas', value: false)

question = Question.create(question: '¿Cómo debo hidratarme en una inundación?', reason: 'En caso de una inundación se recomienda tomar solo agua embotellada sellada, ya que de las canillas podría salir agua contaminada')
Answer.create(question: question, answer: 'Con agua embotellada sellada', value: true)
Answer.create(question: question, answer: 'Con agua de la canilla', value: false)
Answer.create(question: question, answer: 'Con agua de la inundación', value: false)
Answer.create(question: question, answer: 'No debo hidratarme', value: false)

question = Question.create(question: '¿Qué debo hacer con los alimentos que hayan estado en contacto con el agua?', reason: 'Es recomendable evitar el consumo de cualquier alimento que haya estado en contacto con agua de inundación, ya que existe el riesgo de que esté contaminado')
Answer.create(question: question, answer: 'Tirarlos a la basura', value: true)
Answer.create(question: question, answer: 'Comerlos', value: false)
Answer.create(question: question, answer: 'Donarlos', value: false)
Answer.create(question: question, answer: 'Esconderlos', value: false)

question = Question.create(question: '¿Qué debo utilizar para limpiar luego de una inundación?', reason: 'Al momento de hacer una limpieza luego de una inundación, lo mejor es hacer una desinfección utilizando una taza de lavandina cada 10 litros de agua')
Answer.create(question: question, answer: 'Lavandina rebajada con agua', value: true)
Answer.create(question: question, answer: 'Kerosene', value: false)
Answer.create(question: question, answer: 'Agua sucia', value: false)
Answer.create(question: question, answer: 'Jugo', value: false)

